// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANsqKSCB5CKx0mYuP83TBp0YJsK4dK7Fw',
    appId: '1:899539591075:android:db19f14aa7af5098864416',
    messagingSenderId: '899539591075',
    projectId: 'ostad-batch-fourteen',
    databaseURL: 'https://ostad-batch-fourteen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ostad-batch-fourteen.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeXgbMy0FiVTZ3wumM-SvZKjj2PSGvuq0',
    appId: '1:899539591075:ios:4bc794a09784b9ff864416',
    messagingSenderId: '899539591075',
    projectId: 'ostad-batch-fourteen',
    databaseURL: 'https://ostad-batch-fourteen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ostad-batch-fourteen.firebasestorage.app',
    iosClientId: '899539591075-eo3hkush0ljb7ugv65crjortgciv206d.apps.googleusercontent.com',
    iosBundleId: 'com.ostad.craftyBay',
  );
}
